namespace VeloBrawl.Supercell.Titan.CommonUtils.Utils;

public enum ShopItemHelperTable
{
    FreeBox = 0,
    BrawlBox = 6,
    BigBox = 14,
    MegaBox = 10,
    Ticket = 7,
    HeroPower = 8,
    WildcardPower = 12,
    CoinDoubler = 9,
    Keys = 11,
    EventSlot = 13,
    AdBox = 15,
    Coin = 1,
    Gems = 16,
    StarPoints = 17,
    BrawlPassTokens = 28,
    Emote = 19,
    EmoteBundle = 20,
    RandomEmotes = 21,
    RandomEmotesForBrawler = 22,
    RandomEmoteOfRarity = 23,
    RandomEmotesPackOfRarity = 27,
    PlayerThumbnail = 25,
    GuaranteedBox = 2,
    GuaranteedHero = 3,
    Skin = 4,
    SkinAndHero = 24,
    PurchaseOptionSkin = 26,
    Item = 5,
    ClubFeature = 29,
    GuaranteedHeroWithLevel = 30,
    GuaranteedBoxWithLevel = 31,
    GearToken = 32,
    GearScrap = 33,
    Spray = 35
}